(() => {
  const $ = (q) => document.querySelector(q), canvas = $('#shooter-canvas'), ctx = canvas.getContext('2d');
  const colors = ['#ff4f8c', '#68d8ff', '#cffb4b', '#c38cff'], rows = 10, cols = 9, radius = 25;
  let grid, aim = { x: 300, y: 220 }, active = false, shot, frame, queue;
  const pos = (row, col) => ({ x: 55 + col * 62 + (row % 2) * 31, y: 48 + row * 54 });
  const random = () => Math.random() < .1 ? (Math.random() < .5 ? 'bomb' : 'rainbow') : colors[Math.floor(Math.random() * colors.length)];
  const around = (row, col) => (row % 2 ? [[0,-1],[0,1],[-1,0],[-1,1],[1,0],[1,1]] : [[0,-1],[0,1],[-1,-1],[-1,0],[1,-1],[1,0]])
    .map(([a,b]) => [row + a, col + b]).filter(([a,b]) => a >= 0 && a < rows && b >= 0 && b < cols);
  const bubble = (x, y, color) => { ctx.beginPath(); ctx.arc(x, y, radius, 0, Math.PI * 2); ctx.fillStyle = color; ctx.shadowColor = color; ctx.shadowBlur = 15; ctx.fill(); ctx.shadowBlur = 0; ctx.fillStyle = '#ffffff88'; ctx.beginPath(); ctx.arc(x - 8, y - 8, 7, 0, Math.PI * 2); ctx.fill(); };
  function reset() { grid = Array.from({ length: rows }, (_, r) => Array.from({ length: cols }, (_, c) => r < 5 ? colors[(r + c * 2) % colors.length] : null)); queue = [random(),random(),random()]; shot = null; }
  function guide() { let x = 300, y = 548, dx = aim.x - x, dy = Math.min(-20, aim.y - y), length = Math.hypot(dx, dy), vx = dx / length, vy = dy / length; ctx.setLineDash([6,9]); ctx.strokeStyle = '#cffb4b'; ctx.lineWidth = 2; ctx.beginPath(); ctx.moveTo(x,y); for (let i = 0; i < 34; i += 1) { x += vx * 14; y += vy * 14; if (x < radius || x > 600 - radius) { vx *= -1; x = Math.max(radius, Math.min(600 - radius, x)); } ctx.lineTo(x,y); } ctx.stroke(); ctx.setLineDash([]); }
  function draw() { ctx.fillStyle = '#142226'; ctx.fillRect(0,0,600,600); grid.forEach((line,r) => line.forEach((color,c) => { if (color) { const p = pos(r,c); bubble(p.x,p.y,color==='bomb'?'#ff934f':color==='rainbow'?'#fff':color); } })); if (active && !shot) guide(); bubble(300,548,queue[0]==='bomb'?'#ff934f':queue[0]==='rainbow'?'#fff':queue[0]); queue.slice(1).forEach((color,index)=>bubble(525,520-index*55,color==='bomb'?'#ff934f':color==='rainbow'?'#fff':color)); ctx.fillStyle='#b8c7bf';ctx.font='10px monospace';ctx.fillText('NEXT',505,390); if (shot) bubble(shot.x,shot.y,shot.color==='bomb'?'#ff934f':shot.color==='rainbow'?'#fff':shot.color); }
  function sameGroup(row, col, color, seen = new Set()) { const key = `${row},${col}`; if (seen.has(key) || grid[row]?.[col] !== color) return seen; seen.add(key); around(row,col).forEach(([a,b]) => sameGroup(a,b,color,seen)); return seen; }
  function dropFloaters(){const connected=new Set(),visit=(r,c)=>{const k=`${r},${c}`;if(connected.has(k)||!grid[r]?.[c])return;connected.add(k);around(r,c).forEach(([a,b])=>visit(a,b))};grid[0].forEach((v,c)=>visit(0,c));grid.forEach((line,r)=>line.forEach((v,c)=>{if(v&&!connected.has(`${r},${c}`))grid[r][c]=null}))}
  function attach() { let nearest, distance = Infinity; grid.forEach((line,r) => line.forEach((color,c) => { if (color) { const p = pos(r,c), d = Math.hypot(p.x-shot.x,p.y-shot.y); if (d < distance) { distance = d; nearest = [r,c]; } } })); let options = nearest ? around(...nearest).filter(([r,c]) => !grid[r][c]) : []; if (!options.length) options = [[0, Math.max(0,Math.min(cols-1,Math.round((shot.x-55)/62)))]]; const cell = options.reduce((best, option) => Math.hypot(pos(...option).x-shot.x,pos(...option).y-shot.y) < Math.hypot(pos(...best).x-shot.x,pos(...best).y-shot.y) ? option : best); grid[cell[0]][cell[1]] = shot.color; if(shot.color==='bomb')around(...cell).concat([cell]).forEach(([r,c])=>grid[r][c]=null); else { const match=shot.color==='rainbow'&&nearest?grid[nearest[0]][nearest[1]]:shot.color,group=sameGroup(cell[0],cell[1],match); if(group.size>=3){group.forEach(key=>{const[r,c]=key.split(',').map(Number);grid[r][c]=null});dropFloaters()} } shot=null;queue.push(random());queue.shift();draw(); if(grid.slice(rows-2).flat().some(Boolean))lose(); }
  function lose(){active=false;$('#shooter-title').textContent='CLUSTER BREACH';$('#shooter-message').textContent='The bubbles reached the danger line. Clear the grid before it closes in.';$('#shooter-start').innerHTML='TRY AGAIN <b>→</b>';$('#shooter-overlay').hidden=false;}
  function tick() { if (!shot) return; shot.x += shot.vx; shot.y += shot.vy; if (shot.x < radius || shot.x > 600-radius) { shot.vx *= -1; shot.x = Math.max(radius,Math.min(600-radius,shot.x)); } let hit = shot.y < radius; grid.forEach((line,r) => line.forEach((color,c) => { if (color && Math.hypot(pos(r,c).x-shot.x,pos(r,c).y-shot.y) < radius*2-3) hit = true; })); if (hit) attach(); draw(); if (shot) frame=requestAnimationFrame(tick); }
  function point(e) { const rect = canvas.getBoundingClientRect(); aim = { x:(e.clientX-rect.left)*600/rect.width, y:(e.clientY-rect.top)*600/rect.height }; draw(); }
  canvas.addEventListener('pointermove', (e) => { if (active && !shot) point(e); }); canvas.addEventListener('pointerdown', (e) => { if (!active || shot) return; point(e); let dx=aim.x-300,dy=Math.min(-20,aim.y-548),l=Math.hypot(dx,dy); shot={x:300,y:548,vx:dx/l*10,vy:dy/l*10,color:queue[0]}; cancelAnimationFrame(frame); frame=requestAnimationFrame(tick); });
  document.querySelectorAll('.arcade-tab').forEach((button) => button.addEventListener('click', () => { if (button.dataset.game !== 'shooter') return; ['snake-game','minesweeper-game','breakout-game'].forEach((id)=>$('#'+id).hidden=true); $('#shooter-game').hidden=false; $('#arcade').classList.remove('mine-mode'); document.querySelectorAll('.arcade-tab').forEach((tab)=>tab.classList.toggle('active',tab===button)); draw(); }));
  $('#shooter-start').onclick=()=>{ active=true; $('#shooter-overlay').hidden=true; reset(); draw(); }; reset(); draw();
})();
